<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Production admin compatibility fixes discovered during DEV acceptance.
 *
 * 1. WooCommerce settings historically redirect to a non-registered page slug
 *    after a successful save. Rewrite that redirect to the canonical UFSC menu.
 * 2. The admin duplicate-identity SQL historically compares name + first name +
 *    birth date across every season. A normal annual renewal is therefore shown
 *    as a duplicate of its archived source. Scope that comparison to the same
 *    stored season without mutating any licence row.
 */

/**
 * Rewrite the obsolete post-save WooCommerce settings route.
 *
 * @param string $location Redirect target.
 * @param int    $status   HTTP status.
 * @return string
 */
function ufsc_production_fix_woocommerce_settings_redirect( $location, $status ) {
    unset( $status );

    if ( ! is_string( $location ) || false === strpos( $location, 'page=ufsc-woocommerce-settings' ) ) {
        return $location;
    }

    return str_replace( 'page=ufsc-woocommerce-settings', 'page=ufsc-woocommerce', $location );
}
add_filter( 'wp_redirect', 'ufsc_production_fix_woocommerce_settings_redirect', 998, 2 );

/**
 * Register a tightly-scoped SQL compatibility filter on licence admin lists.
 * Database helpers are resolved before the global `query` filter is attached to
 * avoid recursion inside wpdb::query().
 */
function ufsc_production_register_same_season_duplicate_filter() {
    if ( ! is_admin() || ! is_user_logged_in() ) {
        return;
    }

    $page = isset( $_GET['page'] ) && ! is_array( $_GET['page'] )
        ? sanitize_key( wp_unslash( $_GET['page'] ) )
        : '';
    $licence_pages = array( 'ufsc_lc_licences', 'ufsc-gestion-licences', 'ufsc-licences', 'ufsc-sql-licences', 'ufsc-sql-licenses' );
    if ( ! in_array( $page, $licence_pages, true ) || ! function_exists( 'ufsc_get_licences_table' ) ) {
        return;
    }

    $table = (string) ufsc_get_licences_table();
    if ( '' === $table ) {
        return;
    }

    $season_column = '';
    if ( function_exists( 'ufsc_get_detected_season_column' ) ) {
        $season_column = (string) ufsc_get_detected_season_column( $table );
    }

    if ( '' === $season_column ) {
        global $wpdb;
        $columns = function_exists( 'ufsc_table_columns' )
            ? (array) ufsc_table_columns( $table )
            : (array) $wpdb->get_col( "SHOW COLUMNS FROM `{$table}`", 0 );
        foreach ( array( 'season', 'saison', 'paid_season', 'season_end_year' ) as $candidate ) {
            if ( in_array( $candidate, $columns, true ) ) {
                $season_column = $candidate;
                break;
            }
        }
    }

    $season_column = preg_replace( '/[^a-zA-Z0-9_]/', '', $season_column );
    if ( '' === $season_column ) {
        return;
    }

    $GLOBALS['ufsc_production_duplicate_table'] = $table;
    $GLOBALS['ufsc_production_duplicate_season_column'] = $season_column;
    add_filter( 'query', 'ufsc_production_scope_duplicate_identity_to_same_season', 998 );
}
add_action( 'admin_init', 'ufsc_production_register_same_season_duplicate_filter', 50 );

/**
 * Add same-season equality to the legacy duplicate-identity EXISTS subquery.
 *
 * The callback performs no database access. It only touches the exact licence
 * table query shape containing aliases `l` and `l2` generated by SQL admin.
 *
 * @param string $query SQL query.
 * @return string
 */
function ufsc_production_scope_duplicate_identity_to_same_season( $query ) {
    if ( ! is_string( $query ) ) {
        return $query;
    }

    $table = isset( $GLOBALS['ufsc_production_duplicate_table'] )
        ? (string) $GLOBALS['ufsc_production_duplicate_table']
        : '';
    $season_column = isset( $GLOBALS['ufsc_production_duplicate_season_column'] )
        ? (string) $GLOBALS['ufsc_production_duplicate_season_column']
        : '';

    if ( '' === $table || '' === $season_column || false === strpos( $query, $table ) || false === stripos( $query, 'EXISTS' ) ) {
        return $query;
    }

    $same_season_sql = "l2.`{$season_column}` <=> l.`{$season_column}`";
    if ( false !== strpos( $query, $same_season_sql ) ) {
        return $query;
    }

    // The duplicate detector always starts its correlated subquery with
    // `WHERE l2.<pk> <> l.<pk>`. Add the season condition exactly there.
    $pattern = '/(WHERE\s+l2\.`[^`]+`\s*<>\s*l\.`[^`]+`)/i';
    $replacement = '$1 AND ' . $same_season_sql;
    $scoped = preg_replace( $pattern, $replacement, $query, 1 );

    return is_string( $scoped ) ? $scoped : $query;
}
